openapi: 3.2.0
info:
  contact: {}
  description: 'Public API designed to help our partners to automate their tasks.

    Log in to Management Console, create API Key for your automation or reporting process and provide it in "Authorization" header per every request.'
  title: Impossible Cloud Management Console public Integrations API
  version: '1.0'
servers:
- url: https://api.partner.impossiblecloud.com/v1
tags:
- name: Integrations
paths:
  /integration/regions/list:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ListRegionsResponse'
      summary: Lists the available regions
      tags:
      - Integrations
      operationId: getIntegrationRegionsList
      x-operation-id-source: derived
components:
  schemas:
    api.ListRegionsResponse:
      properties:
        regions:
          items:
            $ref: '#/components/schemas/api.Region'
          type: array
      type: object
    api.Region:
      properties:
        iam_url:
          type: string
        name:
          type: string
        s3_url:
          type: string
        sts_url:
          type: string
      type: object
  securitySchemes:
    Bearer:
      description: Type "Bearer" followed by a space and JWT token.
      in: header
      name: Authorization
      type: apiKey
